name: Build and Deploy

on:
  push:
    branches: capstone

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    # Install and build backend
      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: mongodb-express-rest-api/server/package-lock.json

      - name: Install backend dependencies
        working-directory: mongodb-express-rest-api/server
        run: npm install

    # Install and build frontend
      - name: Setup React (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: mongodb-express-rest-api/app/package-lock.json

      - name: Install frontend dependencies
        working-directory: mongodb-express-rest-api/app
        run: npm ci

      - name: Build frontend
        working-directory: mongodb-express-rest-api/app
        run: npm run build
        env:
          CI: false

      # ------------------ DEPLOY TO RENDER ------------------
      - name: Deploy Frontend to Render
        run: |
          curl -X POST "$RENDER_FRONTEND_DEPLOY_HOOK"
        env:
          RENDER_FRONTEND_DEPLOY_HOOK: ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}


      - name: Deploy Backend to Render
        run: |
          curl -X POST "$RENDER_BACKEND_DEPLOY_HOOK"
          echo "✅ Render backend deployment triggered successfully!"
        env:
          RENDER_FRONTEND_DEPLOY_HOOK: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
